Add docker compose and tests

diff --git a/docker-compose.yaml b/docker-compose.yaml
--- a/docker-compose.yaml
+++ b/docker-compose.yaml
@@ -1,14 +1,60 @@
-version: '3'
 services:
   fdb:
-    image: foundationdb/foundationdb:7.3.57
-    ports:
-      - 4550:4550/tcp
+    container_name: fdb
+    image: foundationdb/foundationdb:7.3.68 # no avx
+    platform: "linux/amd64"
     environment:
-      PUBLIC_IP: 0.0.0.0
-      FDB_PROCESS_CLASS: unset
-      FDB_NETWORKING_MODE: host
-      FDB_COORDINATOR_PORT: 4550
-      FDB_PORT: 4550
+      FDB_COORDINATOR: fdb
+      FDB_NETWORKING_MODE: container
+      FDB_COORDINATOR_PORT: 4500
+      FDB_PORT: 4500
+  fdb_setup:
+    container_name: fdb_setup
+    image: foundationdb/foundationdb:7.3.68 # no avx
+    environment:
+      FDB_COORDINATOR: fdb
+      FDB_COORDINATOR_PORT: 4500
+    entrypoint: >
+      bash -c '
+        echo docker:docker@fdb:4500 > /var/fdb/fdb.cluster
+        if ! fdbcli --exec status --timeout 3 ; then
+            echo "creating the database"
+            if ! fdbcli --exec "configure new single ssd ; status" --timeout 10 ; then 
+                echo "Unable to configure new FDB cluster."
+                exit 1
+            fi
+        fi
+      '
+  f8n:
+    container_name: f8n
+    depends_on:
+      - fdb_setup
+    build:
+      context: .
+      dockerfile: Dockerfile
+    command:
+      - --endpoint
+      - "fdb://docker:docker@fdb:4500"
+    environment:
+      LOG_LEVEL: debug
+  k3s:
+    container_name: k3s
+    depends_on:
+      - f8n
+    image: docker.io/rancher/k3s:v1.29.4-k3s1
+    privileged: true
+    command:
+      - server
+      - --disable=servicelb,traefik,local-storage,metrics-server
+      - --kube-apiserver-arg=etcd-compaction-interval=10s
+      - --kube-apiserver-arg=feature-gates=WatchList=true
+      - --disable-network-policy
+      - --flannel-iface=eth0
+    environment:
+      K3S_DATASTORE_ENDPOINT: "http://f8n:2379"
+    volumes:
+      - kubeconfig:/etc/rancher/k3s
 
-# /usr/bin/fdbserver --listen-address 0.0.0.0:"4550" --public-address "0.0.0.0:4550" --datadir /var/fdb/data --logdir /var/fdb/logs --locality-zoneid="$(hostname)" --locality-machineid="$(hostname)"
+volumes:
+  kubeconfig:
+    name: kubeconfig
